### ISSUE TITLE
search is not working with arabic pdf in azure

### ISSUE THREAD

**Issue by ReshmiGitHub** [microsoft/AzureSearch_JFK_Files#101]
Please help to create a site like https://jfkfiles2.azurewebsites.net/  for arabic pdf

**Comment by Careyjmac** [comment]
Shared link is not the one associated with this repository, so closing this issue. For what its worth, this demo should in theory work with Arabic PDFs as well if you make a few small changes (not tested so not for sure this will work, might need some other changes as well):

1. Change [this line](https://github.com/microsoft/AzureSearch_JFK_Files/blob/9ba42347a6285ce0b73b5bcb935e8c84852f9cfc/JfkWebApiSkills/JfkInitializer/SearchResources.cs#L288) to use "generateNormalizedImagePerPage" to ensure that your PDFs will be converted to images and thus can be OCR'd
2. Change [this line](https://github.com/microsoft/AzureSearch_JFK_Files/blob/9ba42347a6285ce0b73b5bcb935e8c84852f9cfc/JfkWebApiSkills/JfkInitializer/SearchResources.cs#L29) to use "OcrSkillLanguage.Ar" so that the OCR will be Arabic.
