### ISSUE TITLE
Indexer warning

### ISSUE THREAD

**Issue by jantielens** [Microsoft/AzureSearch_JFK_Files#15]
I'm trying to deploy this sample, but I get a warning in the Indexer (for every document): 

`Output field mapping target metadata: unable to select property while accessing '/document/hocrDocument/metadata'\r\n"`

The strange thing is that it worked 2 weeks ago ... 

Thanks,
Jan

**Comment by Careyjmac** [comment]
Hi jantielens,

Thank you for reporting this.  We found a bug that seems to have popped up over the last few weeks and have patched it.  If you pull from master and run the JfkInitializer again, everything should work as expected now without this warning.  Please feel free to reach out if you have any additional issues or questions.

Thanks,
Carey MacDonald

**Comment by stevekay72** [comment]
I have the latest version of the code and am getting the same error as the original except that the Metadata is now upper cased for the 'm':

`Output field mapping target metadata: unable to select property while accessing '/document/hocrDocument/Metadata'\r\n"`

Strangely this only happens for some documents and not for all, and I am using my own data rather than the JFK files sample.
