### ISSUE TITLE
How can I execute JfkWebApiSkills project.

### ISSUE THREAD

**Issue by ghost** [microsoft/AzureSearch_JFK_Files#17]
I want to add my testing images in Blobstorage and after that I need to create tag and indexes. So How can I execute this project and add my personal images.

**Comment by Careyjmac** [comment]
Hi sandipArchit,

Are you asking how to use this project on your own data files instead of the sample JFK Files we provided?  If so, then you can redirect the JfkInitializer to point to your own blob storage account by changing the provided keys "JFKFilesBlobStorageAccountConnectionString" and "JFKFilesBlobContainerName" in the App.config file to match your account that contains the files you would like to process.  Alternatively you can change this directly in the code in the "CreateDataSource" method (lines 156-157 of the Program.cs file in the JfkInitializer project).

Do be aware that this particular solution is set up to do things very specific to the JFK Files.  We create some resources that are open to the the internet for access (the website, the additional blob container for the imagestore skill) so if your data needs to remain private and secure you may need to remove these aspects.  The custom skills also might not be useful for your dataset.  I would recommend reading through the [Cognitive Search quickstart tutorial](https://docs.microsoft.com/en-us/azure/search/cognitive-search-quickstart-blob) to better understand how to implement your own skillset for your dataset, though you can also use the code provided here to help you make the necessary requests to get started.

-Carey MacDonald

**Comment by sandipArchit** [comment]
Yes its work for me. But I want to execute other project JfkWebApiSkills and to create FacetGraphNodes, ImageStore because in my customized application everything is working but not grapth node functionality is not working.

**Comment by sandipArchit** [comment]
https://jfk-site-cg6zgjvsynrik.azurewebsites.net/#/search?term=bassole

**Comment by Careyjmac** [comment]
Hi sandipArchit,

You can change the JfkWebApiSkills project directly and then redeploy the Azure Function yourself with your changes.  [Here is a guide](https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs) on development with Azure Functions if you choose to do this.  Also, [here is an example](https://docs.microsoft.com/en-us/azure/search/cognitive-search-create-custom-skill-example) specific to Cognitive Search that shows you what the input and outputs would need to look like if you were to create your own custom skill from scratch, and how to deploy it and integrate it with your skillset.

-Carey MacDonald

**Comment by sandipArchit** [comment]
Sorry I am bothering you. But How can I create Facet Graph. You can see in above screen. It shows only search string but realated search paramter related to entities. When I checked in Azure function. It runs following querystring https://jfk-function-app-cg6zgjvsynrik.azurewebsites.net/api/facet-graph-nodes?code=CJ8wXXFkw6ZptwBmZipGSt1QZ/4sPbXSayj6IpQrNWCplwvMWgscLg==&q=bassole&f=entities adn result is   {"edges":[],"nodes":[{"name":"bassole"}]}

**Comment by BridgetLan** [comment]
Hi Carey,

I was wondering if you could explain a little bit more about resetting the frontend/.env file for each change to the App.config.

I am currently trying to change the connected blob storage account to one of my own test accounts and I want to make sure I'm changing everything that needs to be changed. So far, I have changed the blob storage account connection string and the container name in the App.config file on Visual Studio. I have found lines 156 and 157 and changed those as well, I have manually changed the blob storage connection string in the Functions Application Settings in Azure Portal, and now I'm just trying to figure out this last step so it will hopefully work.

**Comment by Careyjmac** [comment]
Hi @BridgetLan 

Observe lines 317-324 in the Program.cs file to see what I mean about needing to reset the .env file.  If you change any of the keys/values listed on those lines to something else after having already run the Initializer once, the .env file will need to be reset as the find and replace functionality there won't work properly the second time.  Assuming you cloned the repo vs. downloading it, you should be able to use git to reset the file and then run the Initializer with those changes.  Also, since you mention only changing the blob storage settings, it likely shouldn't affect the .env file, but you can confirm by looking at the lines I mentioned above.

One thing I do want to mention is that the blob storage connection string in the function application settings is for a different blob then the source data (which is what it sounds like you changed in the App.config).  You may not actually want that setting to be different, though I obviously don't know what your entire scenario is so I can't say for sure.  For clarity, if you change the "JFKFilesBlobStorageAccountConnectionString" and "JFKFilesBlobContainerName" (the source data) then you won't need to change anything in the Azure Function.  If you change the "BlobStorageAccountConnectionString" setting and the "BlobContainerNameForImageStore" constant in the Program.cs file then you will need to change the Azure Function to accommodate.  Hope that helps.

-Carey

**Comment by BridgetLan** [comment]
Thank you @Careyjmac, I appreciate the clarification. I actually downloaded as a zip file, is there a way to change it from there? Is it possible to just copy a new .env file into the frontend folder? (I know, bad practice but I was hoping it might work). If not, I'll just clone it and start over.

Also, could you tell me what kind of changes could result in the need to reset the .env files? I am looking to change a few other things to match my particular Azure case needs like changing the http trigger to a blob trigger, etc.

**Comment by BridgetLan** [comment]
@Careyjmac Apologies, I just saw the code answers me so you can definitely ignore that last question.

**Comment by BridgetLan** [comment]
![error](https://user-images.githubusercontent.com/43275716/45569336-dd8ae180-b824-11e8-8175-4f497675925f.jpg)
I keep on getting this error. The log file shows:

![error_log_file](https://user-images.githubusercontent.com/43275716/45569626-a832c380-b825-11e8-8bce-c15f9f1be7d4.jpg)

@Careyjmac I don't want to overload you, but do you have any idea what might be causing this? This is using everything with the original instructions and variables, not the ones I will change for my own use.

**Comment by BridgetLan** [comment]
@Careyjmac That is really good to know. I actually cannot see the the files, so I've attached a photo of the Search Service index log file. I'm assuming it has something to do with the permissions.

![jfksearchservice_log_file](https://user-images.githubusercontent.com/43275716/45579834-87339800-b850-11e8-8d71-5c2d4674b580.jpg)

**Comment by Careyjmac** [comment]
@BridgetLan Yea, it looks like something is up with how your Azure Function instance was deployed.  I would try to make sure you have the latest from this repository (there were some fixes recently for some issues with Azure Functions) and then either start from step one of the demo or [redeloy your Azure Function app via Visual Studio ](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-your-first-function-visual-studio#publish-the-project-to-azure) and then run the Initializer again.  Let me know if that helps.

**Comment by BridgetLan** [comment]
It worked the second time around, thank you, @Careyjmac! 

Do you happen to know if there would be a way to change this code to get the indexer to sort important information into a table on a SQL Database? Besides the standard documentation. There are many avenues that keep leading to roadblocks and I'm not sure what best practice would be.

**Comment by Careyjmac** [comment]
You would likely need a custom skill in order to output the information elsewhere.  [You can find documentation on that here](https://docs.microsoft.com/en-us/azure/search/cognitive-search-custom-skill-interface).  Hope it is helpful for your scenario.

**Comment by Careyjmac** [comment]
Closing as this seems to have been resolved and has not had discussion in several months.

**Comment by bora89** [comment]
Hi @Careyjmac . We have the same issue as the author, we do not have graph view working. 
Can you please describe what specifically needs to be done in order to make graph view working?

**Comment by Careyjmac** [comment]
If you changed the search service from the initial ARM template deployment, changing it in the App.config alone is not good enough as we put some of the configuration directly into the Azure Function implementation (which is used to create the graph view) as part of the ARM template.  See[ this comment above](https://github.com/microsoft/AzureSearch_JFK_Files/issues/17#issuecomment-395814058) in order to change the configuration on the Azure function in order for the graph to work.  If there is some other reason it is not working, it may just be that your source files just aren't super compatible with the method we use for generating the graph, so there's not too much I can do to help.

**Comment by bora89** [comment]
Yes, I know that there is come config in the code. But when we change it and then redeploy - it has no difference at all
![c# hard coded config](https://getfile.dokpub.com/yandex/get/https://yadi.sk/i/LpXIa0clVIFxcg)
Although if we hardcode it into headers then it picked it up:
![what we did in request.js](https://getfile.dokpub.com/yandex/get/https://yadi.sk/i/K01qc3Jv46AsKg)

Can you clarify that?

**Comment by Careyjmac** [comment]
Those aren't the configs I was referring to.  The configs I was referring to are for the service name and api key, which are in the [settings.json](https://github.com/microsoft/AzureSearch_JFK_Files/blob/2adaca178394adea5bc813f782110215f24dab26/JfkWebApiSkills/JfkWebApiSkills/local.settings.json#L6) file.  These can be changed on an existing Azure Function without a deployment via the Azure portal, following [the instructions here.](https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-use-azure-function-app-settings#settings)
