### ISSUE TITLE
error running the visual studio project

### ISSUE THREAD

**Issue by hinda00** [microsoft/AzureSearch_JFK_Files#18]
Error creating skillset: Invalid URI: The hostname could not be parsed.

**Comment by Careyjmac** [comment]
Hi hinda00,

Were you able to resolve this problem?  I have never seen this issue myself when running the code from exactly what is given on github, so it could be because you made some customizations that caused it to break?  Did you ensure that the ARM template deployment was a complete success (with no failed resources) before running the JfkInitializer?

If neither of the above are the case, I would recommend deleting your resource group and trying again, making sure to follow the instructions exactly as they are to produce the expected results, as it could just be a transient issue that you saw.

-Carey MacDonald

**Comment by Bougiefever** [comment]
I am having the same issue. When I dig into it, it looks like the credentials for the function app do not allow access. I am getting a 401 error. I got around it for the time being by pasting the url into the browser and hard-coding the json into the app.

**Comment by Careyjmac** [comment]
Closing as this seems to have been resolved and has not had discussion in several months.
