### ISSUE TITLE
Add some details for expected indexing times

### ISSUE THREAD

**Issue by rozele** [microsoft/AzureSearch_JFK_Files#23]
While deploying the default sample and the example set of documents, the indexing process is taking more than 2 hours. I checked how many total documents there were in the provided sample blob store, and it looked like there are 49 documents. I'm not sure what the indexing processing time is for this repo, but it feels like more than a few minutes is too long to index 49 documents. If the long indexing times are expected, can we add a small note about it in the README?

FYI - I deployed using the ARM template to a B1 App Service plan and the Standard tier for Azure Search.

**Comment by Careyjmac** [comment]
Hi Eric,
We are aware of performance issues that Cognitive Search currently had with regards to larger PDFs/documents such as the ones the JFK demo uses and are working on improving it.  For now, with the given demo, even if indexing isn't fully complete, you should be able to start using the provided website to start exploring the data within a minute or two of indexing starting (the first couple of documents usually go pretty fast).  Let me know if that doesn't work for you.
Thanks,
Carey MacDonald

**Comment by Careyjmac** [comment]
If you see data in the search index (via the Search Explorer in the portal for your Azure Search service) but not on the website, you may have deployed the website incorrectly.  In order for the website to work you have to build the website at a very specific time, otherwise the keys for the website to be able to access the search service as well as for accessing the Azure Function for generating the graph will not be in place when you deploy it.  I would try to comment out lines 69-89 in the JfkInitializer in this case (You'll need to add a line to fix instantiation for the bool result as well) and rerun the project, making sure to follow steps 12-15 closely and in the right order.  If the website still doesn't work properly after that, let me know so I can investigate further.

**Comment by Careyjmac** [comment]
Closing as this seems to have been resolved and has not had discussion in several months.  Also, since cognitive search has been announced as GA, the product is 30x faster then it was at this point and the demo now completes in just a few minutes.
