### ISSUE TITLE
Transient Error Search Service

### ISSUE THREAD

**Issue by jakeatmsft** [microsoft/AzureSearch_JFK_Files#62]
Error when running Search Indexer, error description says "Transient Error" when debug turned on

**Comment by stephenhallfr** [comment]
Hi I have the same issue with skill 13.

**Comment by marklmvalencia** [comment]
> Hi
> I also had the issue but when I update the npm....
> at May 2019, some npm update break the code.
> do not update after you do npm install

I agree. The app broke after the npm update.

**Comment by Careyjmac** [comment]
I just did a git clean -xdf and full fresh deployment and rebuild of the website with an updated npm (ran npm i npm as suggested by the install command) and everything was still successful.  Can one of ya'll share a copy of the exact error you are seeing?

**Comment by marklmvalencia** [comment]
Website keys have been set.  Please build the website and then return here and press any key to continue.
Deploying Website...
Deploy website response:

Website deployment accepted.  Waiting for deployment to complete...
Current website deployment status:
Website deployment completed.
Website url: https://xxxxxxxxx.azurewebsites.net/
Waiting for indexing to complete...
**Current indexer status: TransientFailure**
Something went wrong.
Press any key to exit.

**Comment by marklmvalencia** [comment]
> I just did a git clean -xdf and full fresh deployment and rebuild of the website with an updated npm (ran npm i npm as suggested by the install command) and everything was still successful. Can one of ya'll share a copy of the exact error you are seeing?

Website keys have been set.  Please build the website and then return here and press any key to continue.
Deploying Website...
Deploy website response:

Website deployment accepted.  Waiting for deployment to complete...
Current website deployment status:
Website deployment completed.
Website url: https://jfk-site-wwitgamuynkag.azurewebsites.net/
Waiting for indexing to complete...
**Current indexer status: TransientFailure**
Something went wrong.
Press any key to exit.

**Comment by Careyjmac** [comment]
Oh, that is not related to the website or npm build at all, that is related to the indexer in the search service.  I would be most interested in seeing the errors associated with that failure.  You could get those to print out by choosing to print info.LastResult instead of just info.LastResult.Status [here.](https://github.com/microsoft/AzureSearch_JFK_Files/blob/613181e17929a0bf144fd139be2924215c0d6d7b/JfkWebApiSkills/JfkInitializer/Program.cs#L408)  But again, I didn't see this when I ran the demo out of the box myself, so I'm curious if you made any customizations that would have caused this.

**Comment by Careyjmac** [comment]
I am not able to repro this myself with the latest changes, so closing this for now.
