### ISSUE TITLE
Not showing the preview of own PDF's in the Frontend

### ISSUE THREAD

**Issue by WGabriel** [microsoft/AzureSearch_JFK_Files#64]
I uploaded two PDF files with the same content.

1. The first PDF with characters included (= already "OCR'ed").
2. The second PDF containing "screenshots" of the characters.

However, the front-end seems to have problems visualizing the text within the first PDF properly.

![PDF with embedded characters and without](https://user-images.githubusercontent.com/20842206/57451960-dce70580-7262-11e9-87ab-a5bd0a28d706.PNG)

How can I make the results of the first PDF searchable?

**Comment by Careyjmac** [comment]
The results of the first PDF are searchable in that the search service should have extracted the native text as expected.  However, this particular demo and web app experience requires that the text be within an image, as otherwise we wouldn't be able to perform the OCR to grab the bounding boxes that you see in the expanded document experience.

As mentioned in the README, this demo (especially the front end) isn't really meant to work with all document workloads.  I would recommend taking a look at [this demo](https://github.com/LuisCabrer/CognitiveSearchFrontEnd) to see if it would better suit your needs of wanting to be able to explore the native text.  You could also use the Azure portal, go to your search service, and then check out the Search Explorer experience we provided if you want to do searches of your document, but you won't get quite as nice of a front end experience as is provided here.

**Comment by Yazan2** [comment]
Hi @WGabriel 
Did find a way to visualizing the text within the first PDF properly?
