### ISSUE TITLE
All operations successful - no website..

### ISSUE THREAD

**Issue by Parr0t** [microsoft/AzureSearch_JFK_Files#71]
`</body></html>
text:  NEW ORLEANS, LA. 112 723 8 63 
 Lee Harvey Oswald standing in front of a sign  text  person  human face  wall  man  clothing  sketch  drawing  sign  portrait  black and white  posing  handwriting 
entities: System.String[]
cryptonyms: System.String[]
demoBoost: 24
demoInitialPage: 
All operations were successful.
Press any key to exit.`

thats my output from the console but there is no website url :(

**Comment by Careyjmac** [comment]
The indexer probably finished indexing (and the initializer therefore printed the results) before you finished building the website and thus you didn't get time to grab the link.  If you scroll up far enough on this prompt you should still see it.  Otherwise, you should see be able to navigate directly to your Azure Web App in the Azure portal and open it directly from there.

**Comment by Parr0t** [comment]
Okay thanks, found a solution to solve this problem :-)
