### ISSUE TITLE
Problem with indexer 

### ISSUE THREAD

**Issue by dgalvezramos** [microsoft/AzureSearch_JFK_Files#81]
Hello, I get this problem and don't know how to fix it :

Error creating indexer: This indexer refers to a skillset 'azureblob-skillset' that doesn't exist
Something went wrong.

I have created the skillset in my azure search, so don't know why it could not reach it

**Comment by Careyjmac** [comment]
That is odd, but because you are using names defined differently than in this demo, I can't really help you without seeing your configuration to see if it is correct.  I would say to make sure that the names as defined in the App.config are what you expect them to be as those are what is used throughout the demo.  The demo out of the box without any changes works as of #86
